# Generated by Django 4.2.5 on 2023-09-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=35.0, max_digits=5)),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
    ]
