# Generated by Django 4.2.5 on 2023-09-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatelessons',
            name='price',
        ),
        migrations.AlterField(
            model_name='privatelessons',
            name='time_slot',
            field=models.CharField(max_length=10),
        ),
    ]
