# Generated by Django 4.2.5 on 2023-09-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_shoe_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoe_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_sizes',
            field=models.ManyToManyField(blank=True, to='products.shoesize'),
        ),
    ]
