# Generated by Django 4.2.5 on 2023-09-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_shoesize_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shoe_sizes',
        ),
        migrations.DeleteModel(
            name='ShoeSize',
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
